# ベースイメージをNode.js v21のものに変更
FROM node:21-bullseye-slim

WORKDIR /workspace/next_app

# node_modulesディレクトリを作成
RUN mkdir -p /workspace/next_app/node_modules

# package.jsonとpackage-lock.jsonをコピー
COPY next_app/package.json next_app/package-lock.json* ./

# npmを使用して依存関係をインストール
RUN npm install

# ファイルの所有権をnodeユーザーに変更
RUN chown -R node:node ./
USER node

# Next.jsのテレメトリを無効にする
ARG NEXT_TELEMETRY_DISABLED=1
ENV NEXT_TELEMETRY_DISABLED=$NEXT_TELEMETRY_DISABLED

# Next.jsの開発サーバーを起動
CMD ["npm", "run", "dev"]
